version: "3"
services:
  spark:
    container_name: spark
    build: 
      context: .
      dockerfile: spark/Dockerfile
    ports:
      - 8080:8888
    environment: 
      JUPYTER_TOKEN: easy
    volumes: 
      - .:/home/jovyan/
    networks: 
      - elastic

  hadoop:
    image: harisekhon/hadoop:${VERSION:-latest}
    container_name: hadoop
    ports:
      - 8042:8042
      - 8088:8088
      - 19888:19888
      - 50070:50070
      - 50075:50075
    networks: 
      - elastic

  nifi:
    image: apache/nifi
    container_name: nifi
    volumes: 
      - ./hadoop_conf:/opt/nifi/nifi-current/output
    ports:
      - 5000:8080
    networks:
      - elastic
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana
    depends_on: 
      - elasticsearch
    ports:
      - 5600:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic





volumes:
  data01:
    driver: local


networks:
  elastic: