version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.1
    container_name: kibana    
    depends_on: 
      - elasticsearch
    ports:
      - 5600:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.1
    container_name: logstash
    depends_on: 
      - kibana
      - elasticsearch
    ports:
      - 5088:5044
    # command: logstash -f /usr/share/logstash/config/logstash.conf
    volumes:
      - ./logstash_conf/logstash.conf:/usr/share/logstash/config/logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks: 
      - elastic

volumes:
  data01:
    driver: local


networks:
  elastic: