version: "3"
services:
  spark:
    container_name: spark
    build: 
      context: ./spark_conf
      dockerfile: Dockerfile
    ports:
      - 8080:8888
    environment: 
      JUPYTER_TOKEN: easy
    volumes: 
      - .:/home/jovyan/
    networks: 
      - elastic

  hadoop-filebeat:
    container_name: hadoop-filebeat
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    environment:
      - privileged
      - container=docker
    # entrypoint: "filebeat -e -strict.perms=false"
    ports:
      - 8042:8042
      - 8088:8088
      - 19888:19888
      - 50070:50070
      - 50075:50075
      - 5044:5044
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    networks:
      - elastic



  nifi:
    image: apache/nifi
    container_name: nifi
    volumes: 
      - ./hadoop_conf:/opt/nifi/nifi-current/output
    ports:
      - 5000:8080
    networks:
      - elastic


  
volumes:
  data01:
    driver: local


networks:
  elastic: